### ISSUE TITLE
the dataset

### ISSUE THREAD

**Issue by mhlin05** [lcd-dal/feature-extraction-for-CERT-insider-threat-test-dataset#2]
Hello, sir, I am a scholar from China. When I download the dataset from the official website of Carnegie Mellon, the link is always halfway down. How did you download it?

**Comment by lcd-dal** [comment]
I never had the download issue. I'd find a faster/more reliable network if I were in your shoes.

**Comment by mhlin05** [comment]
您的邮件已经收到，谢谢！
