### ISSUE TITLE
Error in feature extraction step 3

### ISSUE THREAD

**Issue by abhishekaken** [lcd-dal/feature-extraction-for-CERT-insider-threat-test-dataset#3]
I am getting this error in step 3 of feature extraction i am not getting what is the issue 
please help me with this 
![Screenshot 2022-04-16 143359](https://user-images.githubusercontent.com/50312245/163669075-7c144da9-788e-42e6-baa9-dea6abcd698b.jpg)
![a](https://user-images.githubusercontent.com/50312245/163669089-7ba57b63-04a7-42cc-8960-08b33f10c9c4.jpg)

**Comment by lcd-dal** [comment]
I suggest to rerun the script on freshly downloaded/extracted CERT r4.2 folder, make sure no errors happens to the download/extract of the raw data. I just reran the script, it works fine in my machine

**Comment by abhishekaken** [comment]
> I suggest to rerun the script on freshly downloaded/extracted CERT r4.2 folder, make sure no errors happens to the download/extract of the raw data. I just reran the script, it works fine in my machine

can u tell me what version of python are u using for this and the version of the joblib,pandas,
and did u run it on linux?

**Comment by lcd-dal** [comment]
Python 3.10 with latest pandas, joblib. 
There IS a device.csv in r4.2 data. That's why I suggest you redownload/reextract the data. Pretty sure that's why you got the error
