### ISSUE TITLE
Not recognising CERT dataset

### ISSUE THREAD

**Issue by Alucard-SOTN** [lcd-dal/feature-extraction-for-CERT-insider-threat-test-dataset#4]
Ive been trying to run the feature_extraction.py file in both a newly decompressed r4.2 and r6.2 folder as you specified, however it constantly throws the exception that it is not placed in a CERT dataset folder. All the packages are installled with the correct versions.

**Comment by lcd-dal** [comment]
That line of code simply checks this `dname not in ['r4.1','r4.2','r6.2','r6.1','r5.1','r5.2']`
So may be you'll need to rename the decompressed folder to one in the list. Sorry for the confusion

**Comment by Alucard-SOTN** [comment]
I see, but the folder is named r6.2 and it still gives the error.

**Comment by lcd-dal** [comment]
You run it on Windows?

**Comment by Alucard-SOTN** [comment]
Yeah, windows 11

**Comment by lcd-dal** [comment]
The code does not support Windows, as stated un README. You'll need to modify the code for it to run on Windows
