### ISSUE TITLE
A question about the columns ‘user’ and ‘pc’.

### ISSUE THREAD

**Issue by GMoverC2x2** [lcd-dal/feature-extraction-for-CERT-insider-threat-test-dataset#7]
Hello, thank you for sharing your work!
I've a question about the columns ‘user’ and ‘pc’. In the resulting file sessionr4.2.csv there are the columns ‘user’ and ‘pc’. My question is whether the ‘pc’ column corresponds to the computers where the user logged in during the period considered. Is that it?

**Comment by luisfredgs** [comment]
Hello,
I have exactly the same question. Does the ‘pc’ column indicate all the computers that the user logged in to?

**Comment by lcd-dal** [comment]
Hi, sorry for late reply. 
The PC encoding can be found here: https://github.com/lcd-dal/feature-extraction-for-CERT-insider-threat-test-datasets/blob/7e1572418d38f805c25846d940aeb7af4eb99e74/feature_extraction.py#L402

Here's where PC-user relateionship is calculated: https://github.com/lcd-dal/feature-extraction-for-CERT-insider-threat-test-datasets/blob/7e1572418d38f805c25846d940aeb7af4eb99e74/feature_extraction.py#L127

The calculation may not be perfect as it's just trying to deduce from the data to see which is most likely a user's PC
